// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igxqxlkogezuivitjdsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlneHF4bGtvZ2V6dWl2aXRqZHN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMzA3NjMsImV4cCI6MjA2MzYwNjc2M30.vwgPtbohngETCW6Xx8sl0ON1VucV97hja3UILU16X6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);